version: '3'

services:
  app1_instancia1:
    build:
      context: .
      dockerfile: app1/Dockerfile
    image: pos-facef/app1:v1.0.0
    restart: always
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
    networks:
      - app-network
  
  app1_instancia2:
    build:
      context: .
      dockerfile: app1/Dockerfile
    image: pos-facef/app1:v1.0.0
    restart: always
    ports:
      - "3002:3000"
    environment:
      PORT: 3000
    networks:
      - app-network
  
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app1/nginx-conf:/etc/nginx/conf.d
    depends_on:
      - app1_instancia1
      - app1_instancia2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge